### ISSUE TITLE
Feature: fail faster if AWS credentials can't be found

### ISSUE THREAD

**Issue by matthewkmayer** [whitfin/s3-meta#5]
https://github.com/rusoto/rusoto/issues/1082 describes this scenario: AWS credentials aren't available locally which causes a 30 second delay before Rusoto reports a failure to find AWS credentials. The ticket also has code showing how to set the timeout for sourcing credentials to prevent that from being an issue.

Making a change in this area lets s3-meta fail faster to let users know what the problem is sooner. 😄

**Comment by whitfin** [comment]
@matthewkmayer aloha, thanks for the issue.

I've been looking through that thread and implemented something similar to what you had (failure on listing buckets) - however I can't seem to replicate the timeout in the first place? If I provide either an invalid key or signature, it fails almost instantly - same thing if I provide the wrong region. 

Do you have any idea how I can cause this timeout so I can test it out? Is it possible that `s3-meta` is not affected somehow?

**Comment by whitfin** [comment]
Ok, strike that - my local was falling back to `~/.aws/credentials`. I nuked that and now I hit the timeout :)

**Comment by whitfin** [comment]
This is closed in https://github.com/whitfin/s3-meta/commit/8caa6c22574233959ef1d48ebe29dbc0e0262526. I added a 500ms timeout - 200ms was probably fine but since 500ms still isn't particularly noticeable, decided to give it that extra few milliseconds ;)

**Comment by softprops** [comment]
Thank you for this!

**Comment by softprops** [comment]
> Ok, strike that - my local was falling back to ~/.aws/credentials. I nuked that and now I hit the timeout :)

btw a great way I found to test was to just not have a "default" profile in my profile chain. I like to force myself to know which account/user Im acting as with `AWS_PROFILE=foo some-aws-tool some args`.
